[options]
admin_passwd = $pbkdf2-sha512$600000$GsNYC2HsvTcGQOjdW8sZow$osoexul0p6nRiEfXPllP2ceU7wUwwLDy0sZgEXZaWI0SwmWe8jDtH5d.ECc4LNbhZfsVTFp5h3DbC1BkX/Z/cw
groq_api_key = [REDACTED]
openrouter_api_key = [REDACTED]
db_host = False
db_port = False
db_user = hadi
db_password = odoo_pwd
addons_path = /home/hadi/odoo19/addons,/home/hadi/odoo19/custom_addons,/home/hadi/odoo19/custom-addons
http_port = 8069
xmlrpc_interface = 0.0.0.0
proxy_mode = True
